In [2]:
import numpy as np

In [3]:
# numpy main datatype is ndarray
a1 = np.array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.2, 3], [1,2,3.5]])
a3 = np.array([[[1, 2.2, 3], [1,2,3.5], [2,3,1]],[[1, 2.2, 3], [1,2,3.5], [2,3,1]] ])

In [6]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [7]:
a1.shape

(3,)

In [8]:
a3.ndim

3

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a3.dtype

dtype('float64')

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.0
1  1.0  2.0  3.5

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 6, 7, 3, 3],
       [9, 2, 5, 1, 6],
       [0, 7, 0, 3, 2]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.87138322, 0.00316178, 0.7925552 ],
       [0.29819933, 0.07845523, 0.83645494],
       [0.6975281 , 0.56163802, 0.8987139 ],
       [0.69379427, 0.87449999, 0.98197224],
       [0.14618956, 0.41040157, 0.62002002]])

In [24]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.33275798, 0.38012418, 0.47743895],
       [0.00736397, 0.70477376, 0.52760936],
       [0.81368334, 0.52525791, 0.73946287],
       [0.31181035, 0.34517936, 0.79222286],
       [0.71040756, 0.16502583, 0.78657999]])

In [25]:
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [26]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [27]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [28]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [31]:
a3

array([[[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]],

       [[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]]])

In [32]:
a2[1]

array([1. , 2. , 3.5])

In [33]:
a3[:2, :2, :2]

array([[[1. , 2.2],
        [1. , 2. ]],

       [[1. , 2.2],
        [1. , 2. ]]])