In [1]:
import numpy as np

In [6]:
# numpy main datatype is ndarray
a1 = np.array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [18]:
a2 = np.array([[1, 2.2, 3], [1,2,3.5]])
a3 = np.array([[[1, 2.2, 3], [1,2,3.5], [2,3,1]],[[1, 2.2, 3], [1,2,3.5], [2,3,1]] ])

In [11]:
a2

array([[1., 2., 3.],
       [1., 2., 3.]])

In [13]:
a1.shape

(3,)

In [22]:
a3.ndim

3

In [ ]:
a3.shape

(2, 3, 3)

In [25]:
a3.dtype

dtype('float64')

In [27]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [34]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.0
1  1.0  2.0  3.5

In [35]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [36]:
sample_array.dtype

dtype('int64')

In [39]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
ones.dtype

dtype('float64')

In [41]:
type(ones)

numpy.ndarray

In [42]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [48]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 0, 0, 3, 1],
       [1, 3, 7, 0, 6],
       [4, 1, 4, 6, 6]])

In [49]:
random_array.size

15

In [50]:
random_array.shape

(3, 5)

In [54]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.51243244, 0.49315607, 0.8666505 ],
       [0.50830519, 0.1552881 , 0.67764945],
       [0.77682826, 0.96232346, 0.07086038],
       [0.31221255, 0.3742306 , 0.85450759],
       [0.45567518, 0.7128616 , 0.71123951]])

In [55]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.02008199, 0.77132062, 0.42202487],
       [0.59841693, 0.25599978, 0.45662008],
       [0.93002562, 0.43394335, 0.13738586],
       [0.11268026, 0.79885603, 0.10468503],
       [0.69704326, 0.16809168, 0.05031163]])

In [56]:
np.random.seed()