In [2]:
import numpy as np

In [3]:
# numpy main datatype is ndarray
a1 = np.array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.2, 3], [1,2,3.5]])
a3 = np.array([[[1, 2.2, 3], [1,2,3.5], [2,3,1]],[[1, 2.2, 3], [1,2,3.5], [2,3,1]] ])

In [6]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [7]:
a1.shape

(3,)

In [8]:
a3.ndim

3

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a3.dtype

dtype('float64')

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.0
1  1.0  2.0  3.5

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 3, 8, 6, 1],
       [3, 8, 7, 1, 3],
       [8, 4, 0, 3, 8]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.65033672, 0.02380863, 0.94597711],
       [0.61060074, 0.14998976, 0.1729261 ],
       [0.06866747, 0.64837389, 0.08438853],
       [0.3385179 , 0.27119485, 0.0221861 ],
       [0.30901362, 0.92876733, 0.19760198]])

In [24]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.46691487, 0.91209875, 0.12075024],
       [0.15875636, 0.82656597, 0.61700101],
       [0.59084849, 0.85609192, 0.19913129],
       [0.51115036, 0.3336947 , 0.66205517],
       [0.43564176, 0.3186591 , 0.79820592]])

In [25]:
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [26]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [27]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [28]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [31]:
a3

array([[[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]],

       [[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]]])

In [32]:
a2[1]

array([1. , 2. , 3.5])

In [33]:
a3[:2, :2, :2]

array([[[1. , 2.2],
        [1. , 2. ]],

       [[1. , 2.2],
        [1. , 2. ]]])

In [34]:
a1 

array([1, 2, 3])

In [35]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [36]:
a1 + ones

array([2., 3., 4.])

In [37]:
a1 - ones

array([0., 1., 2.])

In [38]:
a1 * ones

array([1., 2., 3.])

In [39]:
a2 

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [40]:
a1

array([1, 2, 3])

In [41]:
a1 * a2

array([[ 1. ,  4.4,  9. ],
       [ 1. ,  4. , 10.5]])

In [43]:
a1.shape

(3,)

In [44]:
a2.shape

(2, 3)

In [45]:
a3

array([[[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]],

       [[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]]])

In [47]:
a3.shape

(2, 3, 3)

In [52]:
a1 / a2

array([[1.        , 0.90909091, 1.        ],
       [1.        , 1.        , 0.85714286]])

In [53]:
a2 // a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
a2 ** 2

array([[ 1.  ,  4.84,  9.  ],
       [ 1.  ,  4.  , 12.25]])

In [55]:
np.square(a2)

array([[ 1.  ,  4.84,  9.  ],
       [ 1.  ,  4.  , 12.25]])

In [56]:
np.add(a1, ones)

array([2., 3., 4.])

In [57]:
a1 % 2

array([1, 0, 1], dtype=int32)