In [2]:
import numpy as np

In [3]:
# numpy main datatype is ndarray
a1 = np.array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.2, 3], [1,2,3.5]])
a3 = np.array([[[1, 2.2, 3], [1,2,3.5], [2,3,1]],[[1, 2.2, 3], [1,2,3.5], [2,3,1]] ])

In [6]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [7]:
a1.shape

(3,)

In [8]:
a3.ndim

3

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a3.dtype

dtype('float64')

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.0
1  1.0  2.0  3.5

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 4, 8, 6, 0],
       [7, 7, 6, 8, 0],
       [6, 8, 5, 3, 8]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.31865138, 0.38328678, 0.40525644],
       [0.84759941, 0.43898705, 0.8772465 ],
       [0.52230258, 0.96879772, 0.27175162],
       [0.50822801, 0.57103721, 0.13624238],
       [0.37235002, 0.08306506, 0.31775981]])

In [24]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.60171178, 0.93222371, 0.32885161],
       [0.33423113, 0.2753088 , 0.51382095],
       [0.35150141, 0.0722845 , 0.55137347],
       [0.02174102, 0.80170711, 0.0191144 ],
       [0.53801935, 0.99067327, 0.59617507]])

In [25]:
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [26]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [27]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [28]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [31]:
a3

array([[[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]],

       [[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]]])

In [32]:
a2[1]

array([1. , 2. , 3.5])

In [33]:
a3[:2, :2, :2]

array([[[1. , 2.2],
        [1. , 2. ]],

       [[1. , 2.2],
        [1. , 2. ]]])

In [34]:
a1 

array([1, 2, 3])

In [35]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [36]:
a1 + ones

array([2., 3., 4.])

In [37]:
a1 - ones

array([0., 1., 2.])

In [38]:
a1 * ones

array([1., 2., 3.])

In [39]:
a2 

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [40]:
a1

array([1, 2, 3])

In [41]:
a1 * a2

array([[ 1. ,  4.4,  9. ],
       [ 1. ,  4. , 10.5]])

In [42]:
a1.shape

(3,)

In [43]:
a2.shape

(2, 3)

In [44]:
a3

array([[[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]],

       [[1. , 2.2, 3. ],
        [1. , 2. , 3.5],
        [2. , 3. , 1. ]]])

In [45]:
a3.shape

(2, 3, 3)

In [46]:
a1 / a2

array([[1.        , 0.90909091, 1.        ],
       [1.        , 1.        , 0.85714286]])

In [47]:
a2 // a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
a2 ** 2

array([[ 1.  ,  4.84,  9.  ],
       [ 1.  ,  4.  , 12.25]])

In [49]:
np.square(a2)

array([[ 1.  ,  4.84,  9.  ],
       [ 1.  ,  4.  , 12.25]])

In [50]:
np.add(a1, ones)

array([2., 3., 4.])

In [51]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [52]:
# aggregation = performing the same operation on a number of things
listy_list = [1, 2, 3]
type(listy_list)

list

In [53]:
sum(listy_list)

6

In [54]:
np.sum(listy_list)

6

In [55]:
massive_array = np.random.random(1000)
massive_array

array([2.04849090e-01, 4.90765889e-01, 3.72384689e-01, 4.77401155e-01,
       3.65890386e-01, 8.37917994e-01, 7.68647507e-01, 3.13994677e-01,
       5.72625333e-01, 2.76049048e-01, 4.52842933e-01, 3.52978366e-01,
       6.57399463e-01, 3.70351083e-01, 4.59092978e-01, 7.19324123e-01,
       4.12991829e-01, 9.06423269e-01, 1.80451619e-01, 7.41118873e-01,
       4.22374044e-01, 4.26453573e-01, 6.34379869e-01, 5.22906201e-01,
       4.14885978e-01, 1.42688056e-03, 9.22623458e-02, 7.09394394e-01,
       5.24345597e-01, 6.96160464e-01, 9.55468323e-01, 6.82913854e-01,
       5.31286907e-02, 3.08852685e-01, 5.92594687e-01, 2.35120407e-01,
       9.64971000e-01, 9.45048224e-01, 8.48400881e-01, 4.72323996e-01,
       8.41476715e-01, 1.31110642e-01, 3.08733657e-01, 4.62996394e-01,
       7.41847201e-01, 4.85825229e-01, 1.36876119e-01, 3.43536530e-01,
       3.24426170e-01, 3.00418904e-01, 1.65501400e-01, 4.14901773e-01,
       4.48120658e-01, 7.74900376e-01, 7.96390701e-01, 5.22390128e-01,
      

In [56]:
massive_array[:10]

array([0.20484909, 0.49076589, 0.37238469, 0.47740115, 0.36589039,
       0.83791799, 0.76864751, 0.31399468, 0.57262533, 0.27604905])

In [57]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

45.1 μs ± 279 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.72 μs ± 6.85 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [58]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [59]:
np.mean(a2)

2.1166666666666667

In [60]:
np.max(a2)

3.5

In [61]:
np.min(a2)

1.0

In [62]:
# Variance = measure of the average degree to which each number is different to the mean
# higher variance = wider range of numbers
# lower variance = lower range of numbers 
np.var(a2)

0.8680555555555555

In [63]:
# standard deviation = squareroot of the variance
np.sqrt(np.var(a2))

0.9316949906249123

In [64]:
high_var_array = np.array([1, 100, 1000, 10000])
low_var_array = np.array([2, 4, 6, 8])

In [65]:
np.var(high_var_array), np.var(low_var_array)

(17550487.6875, 5.0)

In [66]:
np.std(high_var_array), np.std(low_var_array)

(4189.330219438425, 2.23606797749979)

In [67]:
np.mean(high_var_array), np.mean(low_var_array)

(2775.25, 5.0)