In [3]:
import numpy as np

In [4]:
# numpy main datatype is ndarray
a1 = np.array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.2, 3], [1,2,3.5]])
a3 = np.array([[[1, 2.2, 3], [1,2,3.5], [2,3,1]],[[1, 2.2, 3], [1,2,3.5], [2,3,1]] ])

In [7]:
a2

array([[1. , 2.2, 3. ],
       [1. , 2. , 3.5]])

In [8]:
a1.shape

(3,)

In [9]:
a3.ndim

3

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a3.dtype

dtype('float64')

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.0
1  1.0  2.0  3.5

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int32')

In [16]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[8, 9, 7, 3, 5],
       [4, 3, 7, 2, 2],
       [7, 2, 1, 6, 5]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.76173307, 0.64225772, 0.95868767],
       [0.24632687, 0.28982784, 0.27813608],
       [0.43710905, 0.20314557, 0.6999395 ],
       [0.94159559, 0.05925404, 0.91700667],
       [0.63488067, 0.47553044, 0.79600866]])

In [25]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.85885105, 0.2889266 , 0.49658916],
       [0.52029633, 0.40162308, 0.06677662],
       [0.34882713, 0.89795009, 0.95189849],
       [0.89615671, 0.66880896, 0.02913125],
       [0.67140518, 0.35301577, 0.03100737]])

In [30]:
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [35]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [37]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.20484909, 0.49076589, 0.37238469],
       [0.47740115, 0.36589039, 0.83791799],
       [0.76864751, 0.31399468, 0.57262533],
       [0.27604905, 0.45284293, 0.35297837],
       [0.65739946, 0.37035108, 0.45909298]])